### ISSUE TITLE
has been blocked by CORS policy

### ISSUE THREAD

**Issue by muffafa** [OmerMohideen/programming-quotes-api#1]
I created next.js app that just tweet random quote. I faced with this issue. I googled it and it says I have to build a proxy. Is there any solution

Access to XMLHttpRequest at 'https://programming-quotesapi.vercel.app/api/random' from origin 'https://tweet-random-programming-quote.vercel.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by OmerMohideen** [comment]
Should be fixed

**Comment by muffafa** [comment]
yes it is working thanks
